[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "code-server --bind-addr 0.0.0.0:$PORT /home/coder/project"
healthcheckPath = "/login"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
