[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "code-server --bind-addr 0.0.0.0:$PORT /home/coder/project"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
